config/routes.rb
Rails.application.routes.draw do

  # Resouce paths
  resources :exercises, except: [:index]
  resources :workouts
  resources :weights
  devise_for :users

  # Home page is root
  root 'home#home'
  get 'home', to: "home#home"

  # Contact page
  get 'contact', to: 'home#contact'
  #post route for the contact form
  post 'request_contact', to: 'home#request_contact'

  #Summary page
  get 'summary', to: 'summary#summary'

end

app/models/workout.rb
class Workout < ApplicationRecord
    #Each workout entry is associated to a user
    belongs_to :user
    #Each workout has many exercises
    has_many :exercises, dependent: :destroy
    #Each workouts must have a date, workout type, and duration 
    validates :date, :workout_type, :duration, presence: true

    #Scope to show workouts only associated to specific user
    scope :user_workouts, ->(user) { where(['user_id = ?', user.id]) }

    #Returns all workouts for this month for a user
    def self.this_month(user)
        return Workout.where(date: Date.current.beginning_of_month..Date.current.end_of_month, :user_id => user.id)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  # Page can only be accessed if user is logged in
  before_action :authenticate_user!

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.user_workouts(current_user).order(params[:sort])
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: I18n.t('workouts.created') }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update

    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: I18n.t('workouts.updated')}
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: I18n.t('workouts.deleted') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:date, :workout_type, :duration, :calories)
    end
end

app/views/workouts/_form.html.haml
%br
%br
= form_for @workout do |f|
  - if @workout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@workout.errors.count, "error")}" + t('.error')
      %ul
        - @workout.errors.full_messages.each do |message|
          %li= message

  -#Form to enter new workout
  %form{'action' => '/action_page.php'}
    .col-xs-3
      .form-group
        = f.label :date
        = f.date_field :date, class: 'form-control'
      .form-group
        = f.label :workout_type
        = f.text_field :workout_type, class: 'form-control'
      .form-group
        = f.label :duration
        = f.number_field :duration, class: 'form-control', min: '1' #Ensures user cannot enter negative time
      .form-group
        = f.label :calories
        = f.number_field:calories, class: 'form-control', min: '1' #Ensures user cannot enter negative calories
      .form-group
        = f.submit t('crud.save'), class: 'btn btn-default'

app/views/workouts/index.html.haml
%h2= t('.title')

-#Link to add a new workout
%i.far.fa-plus-square
= link_to t('workouts.new'), new_workout_path
%br
%br

-#Displays workouts table only if current user has workouts to display
-if current_user.workouts.first.present?
  %table.table.table-bordered.table-hover
    %thread
      %tr
        %th.heading= link_to t('units.date'), :sort => "date"
        %th.heading= link_to t('.workout_type'), :sort => "workout_type"
        %th.heading= link_to t('.duration'), :sort => "duration"
        %th.heading= link_to t('units.calories'), :sort => "calories"
        %th

      %tbody
        -#Displays workouts so that most recent entry is at the top
        - @workouts.reverse_each do |workout|
          %tr.hoverable
            %td= workout.date
            %td= workout.workout_type
            %td= workout.duration
            %td= workout.calories
            %td= link_to t('crud.details'), workout

app/views/workouts/new.html.haml
%h1= t('workouts.new')

= render 'form'

app/views/workouts/show.html.haml
%p
  %b= t('.date')
  = @workout.date
%p
  %b= t('.workout_type')
  = @workout.workout_type
%p
  %b= t('.duration')
  = @workout.duration.to_s + t('units.minutes')
%p
  %b= t('.calories')
  = @workout.calories

= link_to t('crud.edit'), edit_workout_path(@workout)
\|
= link_to t('crud.delete'), @workout, method: :delete, data: { confirm: t('crud.delete_confirm') }

%hr

-#Renders exercises table only if there are exercises to display
= render :partial => "exercises/table" unless @workout.exercises.empty?

-#Link to add new exercise
%i.far.fa-plus-square
= link_to t('.add'), new_exercise_path(workout_id: @workout)