config/routes.rb
Rails.application.routes.draw do

  # Resouce paths
  resources :exercises, except: [:index]
  resources :workouts
  resources :weights
  devise_for :users

  # Home page is root
  root 'home#home'
  get 'home', to: "home#home"

  # Contact page
  get 'contact', to: 'home#contact'
  #post route for the contact form
  post 'request_contact', to: 'home#request_contact'

  #Summary page
  get 'summary', to: 'summary#summary'

end

app/views/shared/_footer.html.haml
%footer
    %p= link_to t('.content'), contact_path

app/views/shared/_header.html.haml
%header
    -#Styled a collapsable navbar
    %nav.navbar.navbar-inverse
        .container-fluid
            .navbar-header
                %button.navbar-toggle{'type' => 'button', 'data-toggle' => 'collapse', 'data-target' => '#myNavbar'}
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
                %a.navbar-brand{'href' => '/home'}= t('app_title')
            #myNavbar.collapse.navbar-collapse
                %ul.nav.navbar-nav.navbar
                    -#Displays links to all the different pages
                    %li=link_to t('.nav_workouts'), workouts_path
                    %li=link_to t('.nav_weights'), weights_path
                    %li=link_to t('.nav_summary'), summary_path
                %ul.nav.navbar-nav.navbar-right
                    %li
                        - if user_signed_in? #Displays user email and logout option if user is logged in
                            %li= link_to "#{current_user.email}", edit_user_registration_path
                            %li= link_to t('.logout'), destroy_user_session_path, method: 'delete'
                        - else  #Else displays login and sign up option
                            %li= link_to t('.login'), new_user_session_path
                            %li= link_to t('.sign_up'), new_user_registration_path
    %br