config/routes.rb
Rails.application.routes.draw do

  # Resouce paths
  resources :exercises, except: [:index]
  resources :workouts
  resources :weights
  devise_for :users

  # Home page is root
  root 'home#home'
  get 'home', to: "home#home"

  # Contact page
  get 'contact', to: 'home#contact'
  #post route for the contact form
  post 'request_contact', to: 'home#request_contact'

  #Summary page
  get 'summary', to: 'summary#summary'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    
    redirect_to contact_path
  end
end

app/views/home/contact.html.haml
%h1= t('.title')
%br
%br
%p= t('.contact_us')

= form_tag request_contact_path, method: 'post', id: "contact_form" do

    -#Contact form for mailer
    %form{'action' => '/action_page.php'}
        .form-group
            = label_tag :name, t('.name')
            = text_field_tag :name, '', title: t('.enter_name'), class: 'form-control'

        .form-group
            = label_tag :email, t('.email')
            = email_field_tag :email, '', title: t('.enter_email'), class: 'form-control'

        .form-group
            = label_tag :telephone, t('.telephone')
            = telephone_field_tag :telephone, '', title: t('.enter_telephone'), class: 'form-control'

        .form-group
            = label_tag :message, t('.message')
            = text_field_tag :message, '', title: t('.enter_message'),class: 'form-control input-lg'

        .form-group
            .col-md-9.col-md-offset-3
                #messages

        .form-group
            = submit_tag t('.send'), class: 'btn btn-default'

app/views/home/home.html.haml
.container-fluid.text-center
    -#Displays logo of website
    %img{:alt => "", :src => "/assets/logo.png", id: 'logo'}
    %h1= t('.welcome')
    %hr

    -#Displays some images of workout and exercises table for homepage
    %img{:alt => "", :src => "/assets/workout_log.png"}
    %img{:alt => "", :src => "/assets/workout_details.png"}

    -#Displays text explaining images
    .home.h4.fas.fa-running= t('.record_workouts')

    %hr

    -#Displays some images of weight table and weight graph for homepage
    %img{:alt => "", :src => "/assets/weight_log.png"}
    %img{:alt => "", :src => "/assets/weight_graph.png"}

    -#Displays text explaining images
    .home.h4.fas.fa-weight= t('.track_weight')

    %hr

    -#Displays image of summary for homepage
    %img{:alt => "", :src => "/assets/summary.png"}

    %br

    -#Displays text explaining images
    .home.h4.fas.fa-fire-alt= t('.stay_motivated')

    %hr
     