config/routes.rb
Rails.application.routes.draw do

  # Resouce paths
  resources :exercises, except: [:index]
  resources :workouts
  resources :weights
  devise_for :users

  # Home page is root
  root 'home#home'
  get 'home', to: "home#home"

  # Contact page
  get 'contact', to: 'home#contact'
  #post route for the contact form
  post 'request_contact', to: 'home#request_contact'

  #Summary page
  get 'summary', to: 'summary#summary'

end

app/models/weight.rb
class Weight < ApplicationRecord
    #Each weight entry is associated to a user
    belongs_to :user
    #Each weight can have one image attached
    has_one_attached :image
    #Each weight entry must have a date and weight
    validates :date, :weight, presence: true

    #Scope to show weights only associated to specific user
    scope :user_weights, ->(user) { where(['user_id = ?', user.id]) }

    #Calculates weight difference for a user
    def self.weight_difference(user)
        #First weight entry of user
        initial = Weight.order('date DESC').where(:user_id => user.id).first
        #Most recent entry of user
        current = Weight.order('date ASC').where(:user_id => user.id).first
        #Calculates the difference
        weight_difference = current.weight - initial.weight
        if weight_difference > 0
            #Makes weight appear as a negative to show weight loss
            return weight_difference *-1
        else 
            #Makes weight appear as a positive to show weight gain
            return weight_difference.abs
        end
    end

    #Returns all weights for this month for a user
    def self.this_month(user)
        return Weight.where(date: Date.current.beginning_of_month..Date.current.end_of_month, :user_id => user.id)
    end

    #Returns first weight entry for a user
    def self.first_weight(user)
        return Weight.order('date ASC').where(:user_id => user.id).first
    end

    #Returns most recent weight entry for a user
    def self.current_weight(user)
        return Weight.order('date DESC').where(:user_id => user.id).first
    end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]
  # Page can only be accessed if user is logged in
  before_action :authenticate_user!

  # GET /weights
  # GET /weights.json
  def index
    @weights = Weight.where(:user_id => current_user.id).order('date ASC')
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
  end

  # GET /weights/new
  def new
    @weight = Weight.new
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  # POST /weights.json
  def create
    @weight = Weight.new(weight_params)
    @weight.user = current_user

    respond_to do |format|
      if @weight.save
        format.html { redirect_to @weight, notice: I18n.t('weights.created') }
        format.json { render :show, status: :created, location: @weight }
      else
        format.html { render :new }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weights/1
  # PATCH/PUT /weights/1.json
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to @weight, notice: I18n.t('weights.updated') }
        format.json { render :show, status: :ok, location: @weight }
      else
        format.html { render :edit }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to weights_url, notice: I18n.t('weights.deleted') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weight_params
      params.require(:weight).permit(:date, :weight, :image)
    end
end

app/views/weights/_form.html.haml
%br
%br
= form_for @weight do |f|
  - if @weight.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weight.errors.count, "error")}" + t('.error')
      %ul
        - @weight.errors.full_messages.each do |message|
          %li= message

  -#Form to enter new weight
  %form{'action' => '/action_page.php'}
    .col-xs-3
      .form-group
        = f.label :date
        = f.date_field :date, class: 'form-control'
      .form-group
        = f.label :weight
        = f.number_field :weight, class: 'form-control', min: '0.0', step: '0.1' #Ensures user cannot enter negative weight
      .form-group
        = f.label t('.progress_picture')
        = f.file_field :image
      .form-group
        = f.submit t('crud.save'), class: 'btn btn-default'

app/views/weights/edit.html.haml
%h1= t('.title')

= render 'form'

app/views/weights/index.html.haml
%h2= t('.title')

-#Only displays content if there is atleast one weight entry
-if current_user.weights.first.present?
  %br
  = line_chart current_user.weights.group_by_week(:date).average(:weight)
  %br
  %div.container-fluid.box_display
    -#Displays total weight change
    %h4.box.fas.fa-weight= t('.weight_change')
    %p.box=  weight_difference.to_s + t('units.kg')
  %hr

-#Link to add a new weight
%i.far.fa-plus-square
= link_to t('weights.new'), new_weight_path
%br

-#Only displays content if there is atleast one weight entry for current user
-if current_user.weights.first.present?
  %br
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th= t('units.date')
        %th= t('.weight')
        %th

    %tbody
      -#Displays weights so most recent entry is at the top
      - @weights.reverse_each do |weight|
        %tr.hoverable
          %td= weight.date
          %td= weight.weight
          %td= link_to t('crud.details'), weight

app/views/weights/new.html.haml
%h1= t('weights.new')

= render 'form'

app/views/weights/show.html.haml
%br
-# If a weight has an image attached then display it
- if @weight.image.attached?
  %image.img-fluid{alt: "Responsive image", src: "#{(url_for(@weight.image))}"}

%p
  %b Date:
  = @weight.date
%p
  %b Weight:
  = @weight.weight.to_s + t('units.kg')

= link_to t('crud.edit'), edit_weight_path(@weight)
\|
= link_to t('crud.delete'), @weight, method: :delete, data: { confirm: t('crud.delete_confirm') }